databases:
  - name: fyp
    databaseName: fyp
    user: fyp

services:
  - type: web
    name: fyp
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn fyp.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase: 
          name: fyp
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
